## Phase 1

In [1]:
#Importing necessary libraries
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
#importing data sets to check for years
a=pd.read_csv(r'D:\India_Crime - Copy\01_District_wise_crimes_committed_IPC_2001_2012.csv')
b=pd.read_csv(r'D:\India_Crime - Copy\02_01_District_wise_crimes_committed_against_SC_2001_2012.csv')

#checking columns of 'a' data frame
a.columns

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')

In [3]:
#checking unique values present in 'YEAR' column of 'a' dataframe
a['YEAR'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012], dtype=int64)

In [4]:
#checking columns of 'b' data frame
b.columns

Index(['STATE/UT', 'DISTRICT', 'Year', 'Murder', 'Rape',
       'Kidnapping and Abduction', 'Dacoity', 'Robbery', 'Arson', 'Hurt',
       'Prevention of atrocities (POA) Act',
       'Protection of Civil Rights (PCR) Act', 'Other Crimes Against SCs'],
      dtype='object')

In [5]:
#checking unique values present in 'Year' column of 'b' dataframe
b['Year'].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012], dtype=int64)

The **data** to be collected should cover the **years** from **2001 to 2012.**

In [6]:
#creating empty data frame
df=pd.DataFrame()

df['STATE/UT']=a['STATE/UT'].drop_duplicates()#storing unique data present in 'STATE/UT' column from 'a' data frame into 'df' data frame

df.reset_index(inplace=True,drop=True)#reseting index

df

             STATE/UT
0      ANDHRA PRADESH
1   ARUNACHAL PRADESH
2               ASSAM
3               BIHAR
4        CHHATTISGARH
5                 GOA
6             GUJARAT
7             HARYANA
8    HIMACHAL PRADESH
9     JAMMU & KASHMIR
10          JHARKHAND
11          KARNATAKA
12             KERALA
13     MADHYA PRADESH
14        MAHARASHTRA
15            MANIPUR
16          MEGHALAYA
17            MIZORAM
18           NAGALAND
19             ODISHA
20             PUNJAB
21          RAJASTHAN
22             SIKKIM
23         TAMIL NADU
24            TRIPURA
25      UTTAR PRADESH
26        UTTARAKHAND
27        WEST BENGAL
28      A & N ISLANDS
29         CHANDIGARH
30       D & N HAVELI
31        DAMAN & DIU
32           DELHI UT
33        LAKSHADWEEP
34         PUDUCHERRY

Data is inserted successfully.

In [7]:
#data is collected from : https://en.wikipedia.org/wiki/List_of_states_in_India_by_past_population

population_in_2001=[75728400, 1098328 , 26638600, 82879910, 20834530, 1348900, 50597200 , 21083900, 6077453, 10070300, 26946070 , 52734986, 31839000, 60385090, 96752500, 2294480, 2306540, 889690, 1990275, 36707900, 24289130, 56473300, 541902, 62111390, 3191880 , 166053600, 8489100, 80221300, 356650, 901080, 220963, 158080, 13851503, 61300, 974820]

population_in_2011=[49386799, 1382611, 31169272, 103804630, 25540196, 1457723, 60383628 , 25753081, 6856509, 12548926, 32988134, 61130704, 33387677, 72597565, 112372972, 2721756,  2964007, 1091014, 1980602, 41947358, 27704236, 68621012, 607688, 72138958, 3671032, 199581477, 10116752 , 91347736, 379944, 1054686, 342853, 242911, 16753235, 64429, 1244464]

In [8]:
df['population_2001']=population_in_2001 #inserting data of 'population_in_2001' in 'df' data frame

df['population_2011']=population_in_2011 #inserting data of 'population_in_2011' in 'df' data frame

df

             STATE/UT  population_2001  population_2011
0      ANDHRA PRADESH         75728400         49386799
1   ARUNACHAL PRADESH          1098328          1382611
2               ASSAM         26638600         31169272
3               BIHAR         82879910        103804630
4        CHHATTISGARH         20834530         25540196
5                 GOA          1348900          1457723
6             GUJARAT         50597200         60383628
7             HARYANA         21083900         25753081
8    HIMACHAL PRADESH          6077453          6856509
9     JAMMU & KASHMIR         10070300         12548926
10          JHARKHAND         26946070         32988134
11          KARNATAKA         52734986         61130704
12             KERALA         31839000         33387677
13     MADHYA PRADESH         60385090         72597565
14        MAHARASHTRA         96752500        112372972
15            MANIPUR          2294480          2721756
16          MEGHALAYA          2306540          2964007
17            MIZORAM           889690          1091014
18           NAGALAND          1990275          1980602
19             ODISHA         36707900         41947358
20             PUNJAB         24289130         27704236
21          RAJASTHAN         56473300         68621012
22             SIKKIM           541902           607688
23         TAMIL NADU         62111390         72138958
24            TRIPURA          3191880          3671032
25      UTTAR PRADESH        166053600        199581477
26        UTTARAKHAND          8489100         10116752
27        WEST BENGAL         80221300         91347736
28      A & N ISLANDS           356650           379944
29         CHANDIGARH           901080          1054686
30       D & N HAVELI           220963           342853
31        DAMAN & DIU           158080           242911
32           DELHI UT         13851503         16753235
33        LAKSHADWEEP            61300            64429
34         PUDUCHERRY           974820          1244464

Data is inserted successfully.

According to the census, **data is only available** for the years **2001 and 2011.** Therefore, we can make **assumptions** for the **remaining years** by estimating **average annual growth.**

In [9]:
#creating empty lists
population_in_2002=[]
population_in_2003=[]
population_in_2004=[]
population_in_2005=[]
population_in_2006=[]
population_in_2007=[]
population_in_2008=[]
population_in_2009=[]
population_in_2010=[]
population_in_2012=[]

for i in range(0,35):#running loop for 35 times
    
    p_2011=df.iloc[i,-1] #storing population of 2011 year
    
    p_2001=df.iloc[i,-2] #storing population of 2001 year

    diff=p_2011-p_2001 #calculating difference
    
    last_digit=diff%10 #fetching last digit of 'diff'
    
    if last_digit!=0: #using if condition to check if last digit of the number is zero or not
        
        diff=diff-last_digit #subtracting last digit from the 'diff'
        
    avg=diff//10 #calculating average
    
    population_in_2002.append(p_2001+avg) #appending  sum of 'avg' and 'p_2001'
     
    population_in_2003.append(population_in_2002[i]+avg) #appending sum of 'avg' and 'population_in_2002'
    
    population_in_2004.append(population_in_2003[i]+avg) #appending sum of 'avg' and 'population_in_2003'
    
    population_in_2005.append(population_in_2004[i]+avg) #appending sum of 'avg' and 'population_in_2004'
    
    population_in_2006.append(population_in_2005[i]+avg) #appending sum of 'avg' and 'population_in_2005' 
    
    population_in_2007.append(population_in_2006[i]+avg) #appending sum of 'avg' and 'population_in_2006'
    
    population_in_2008.append(population_in_2007[i]+avg) #appending sum of 'avg' and 'population_in_2007'
    
    population_in_2009.append(population_in_2008[i]+avg) #appending sum of 'avg' and 'population_in_2008'
    
    population_in_2010.append(population_in_2009[i]+avg+last_digit)  #appending  sum of 'avg', 'population_in_2009' and 'last_digit' (which was removed from the diff) 
    
    population_in_2012.append(population_in_2011[i]+avg) #appending  sum of 'avg' and 'population_in_2011' 
    

df['population_2001']=population_in_2001 #inserting data of 'population_in_2001' in 'df' data frame

df['population_2002']=population_in_2002 #inserting data of 'population_in_2002' in 'df' data frame

df['population_2003']=population_in_2003 #inserting data of 'population_in_2003' in 'df' data frame

df['population_2004']=population_in_2004 #inserting data of 'population_in_2004' in 'df' data frame

df['population_2005']=population_in_2005 #inserting data of 'population_in_2005' in 'df' data frame

df['population_2006']=population_in_2006 #inserting data of 'population_in_2006' in 'df' data frame

df['population_2007']=population_in_2007 #inserting data of 'population_in_2007' in 'df' data frame

df['population_2008']=population_in_2008 #inserting data of 'population_in_2008' in 'df' data frame

df['population_2009']=population_in_2009 #inserting data of 'population_in_2009' in 'df' data frame

df['population_2010']=population_in_2010 #inserting data of 'population_in_2010' in 'df' data frame

df['population_2012']=population_in_2012 #inserting data of 'population_in_2012' in 'df' data frame

df

,STATE/UT,population_2001,population_2011,population_2002,population_2003,population_2004,population_2005,population_2006,population_2007,population_2008,population_2009,population_2010,population_2012
0,ANDHRA PRADESH,75728400,49386799,73094239,70460078,67825917,65191756,62557595,59923434,57289273,54655112,52020960,46752638
1,ARUNACHAL PRADESH,1098328,1382611,1126756,1155184,1183612,1212040,1240468,1268896,1297324,1325752,1354183,1411039
2,ASSAM,26638600,31169272,27091667,27544734,27997801,28450868,28903935,29357002,29810069,30263136,30716205,31622339
3,BIHAR,82879910,103804630,84972382,87064854,89157326,91249798,93342270,95434742,97527214,99619686,101712158,105897102
4,CHHATTISGARH,20834530,25540196,21305096,21775662,22246228,22716794,23187360,23657926,24128492,24599058,25069630,26010762
5,GOA,1348900,1457723,1359782,1370664,1381546,1392428,1403310,1414192,1425074,1435956,1446841,1468605
6,GUJARAT,50597200,60383628,51575842,52554484,53533126,54511768,55490410,56469052,57447694,58426336,59404986,61362270
7,HARYANA,21083900,25753081,21550818,22017736,22484654,22951572,23418490,23885408,24352326,24819244,25286163,26219999
8,HIMACHAL PRADESH,6077453,6856509,6155358,6233263,6311168,6389073,6466978,6544883,6622788,6700693,6778604,6934414
9,JAMMU & KASHMIR,10070300,12548926,10318162,10566024,10813886,11061748,11309610,11557472,11805334,12053196,12301064,12796788
10,JHARKHAND,26946070,32988134,27550276,28154482,28758688,29362894,29967100,30571306,31175512,31779718,32383928,33592340
11,KARNATAKA,52734986,61130704,53574557,54414128,55253699,56093270,56932841,57772412,58611983,59451554,60291133,61970275
12,KERALA,31839000,33387677,31993867,32148734,32303601,32458468,32613335,32768202,32923069,33077936,33232810,33542544
13,MADHYA PRADESH,60385090,72597565,61606337,62827584,64048831,65270078,66491325,67712572,68933819,70155066,71376318,73818812
14,MAHARASHTRA,96752500,112372972,98314547,99876594,101438641,103000688,104562735,106124782,107686829,109248876,110810925,113935019
15,MANIPUR,2294480,2721756,2337207,2379934,2422661,2465388,2508115,2550842,2593569,2636296,2679029,2764483
16,MEGHALAYA,2306540,2964007,2372286,2438032,2503778,2569524,2635270,2701016,2766762,2832508,2898261,3029753
17,MIZORAM,889690,1091014,909822,929954,950086,970218,990350,1010482,1030614,1050746,1070882,1111146
18,NAGALAND,1990275,1980602,1989307,1988339,1987371,1986403,1985435,1984467,1983499,1982531,1981570,1979634
19,ODISHA,36707900,41947358,37231845,37755790,38279735,38803680,39327625,39851570,40375515,40899460,41423413,42471303
20,PUNJAB,24289130,27704236,24630640,24972150,25313660,25655170,25996680,26338190,26679700,27021210,27362726,28045746
21,RAJASTHAN,56473300,68621012,57688071,58902842,60117613,61332384,62547155,63761926,64976697,66191468,67406241,69835783
22,SIKKIM,541902,607688,548480,555058,561636,568214,574792,581370,587948,594526,601110,614266
23,TAMIL NADU,62111390,72138958,63114146,64116902,65119658,66122414,67125170,68127926,69130682,70133438,71136202,73141714
24,TRIPURA,3191880,3671032,3239795,3287710,3335625,3383540,3431455,3479370,3527285,3575200,3623117,3718947
25,UTTAR PRADESH,166053600,199581477,169406387,172759174,176111961,179464748,182817535,186170322,189523109,192875896,196228690,202934264
26,UTTARAKHAND,8489100,10116752,8651865,8814630,8977395,9140160,9302925,9465690,9628455,9791220,9953987,10279517
27,WEST BENGAL,80221300,91347736,81333943,82446586,83559229,84671872,85784515,86897158,88009801,89122444,90235093,92460379
28,A & N ISLANDS,356650,379944,358979,361308,363637,365966,368295,370624,372953,375282,377615,382273
29,CHANDIGARH,901080,1054686,916440,931800,947160,962520,977880,993240,1008600,1023960,1039326,1070046
30,D & N HAVELI,220963,342853,233152,245341,257530,269719,281908,294097,306286,318475,330664,355042
31,DAMAN & DIU,158080,242911,166563,175046,183529,192012,200495,208978,217461,225944,234428,251394
32,DELHI UT,13851503,16753235,14141676,14431849,14722022,15012195,15302368,15592541,15882714,16172887,16463062,17043408
33,LAKSHADWEEP,61300,64429,61612,61924,62236,62548,62860,63172,63484,63796,64117,64741
34,PUDUCHERRY,974820,1244464,1001784,1028748,1055712,1082676,1109640,1136604,1163568,1190532,1217500,1271428

In [10]:
#rearranging 'population_2011' column in the data frame
c=df['population_2011'] #copying 'population_2011' data into 'c' variable

d=df['population_2012'] #copying 'population_2012' data  into 'd' variable

df.drop(['population_2011','population_2012'],axis=1,inplace=True) #dropping 'population_2011' and 'population_2012' columns

#re-adding columns
df['population_2011']=c 

df['population_2012']=d

df

,STATE/UT,population_2001,population_2002,population_2003,population_2004,population_2005,population_2006,population_2007,population_2008,population_2009,population_2010,population_2011,population_2012
0,ANDHRA PRADESH,75728400,73094239,70460078,67825917,65191756,62557595,59923434,57289273,54655112,52020960,49386799,46752638
1,ARUNACHAL PRADESH,1098328,1126756,1155184,1183612,1212040,1240468,1268896,1297324,1325752,1354183,1382611,1411039
2,ASSAM,26638600,27091667,27544734,27997801,28450868,28903935,29357002,29810069,30263136,30716205,31169272,31622339
3,BIHAR,82879910,84972382,87064854,89157326,91249798,93342270,95434742,97527214,99619686,101712158,103804630,105897102
4,CHHATTISGARH,20834530,21305096,21775662,22246228,22716794,23187360,23657926,24128492,24599058,25069630,25540196,26010762
5,GOA,1348900,1359782,1370664,1381546,1392428,1403310,1414192,1425074,1435956,1446841,1457723,1468605
6,GUJARAT,50597200,51575842,52554484,53533126,54511768,55490410,56469052,57447694,58426336,59404986,60383628,61362270
7,HARYANA,21083900,21550818,22017736,22484654,22951572,23418490,23885408,24352326,24819244,25286163,25753081,26219999
8,HIMACHAL PRADESH,6077453,6155358,6233263,6311168,6389073,6466978,6544883,6622788,6700693,6778604,6856509,6934414
9,JAMMU & KASHMIR,10070300,10318162,10566024,10813886,11061748,11309610,11557472,11805334,12053196,12301064,12548926,12796788
10,JHARKHAND,26946070,27550276,28154482,28758688,29362894,29967100,30571306,31175512,31779718,32383928,32988134,33592340
11,KARNATAKA,52734986,53574557,54414128,55253699,56093270,56932841,57772412,58611983,59451554,60291133,61130704,61970275
12,KERALA,31839000,31993867,32148734,32303601,32458468,32613335,32768202,32923069,33077936,33232810,33387677,33542544
13,MADHYA PRADESH,60385090,61606337,62827584,64048831,65270078,66491325,67712572,68933819,70155066,71376318,72597565,73818812
14,MAHARASHTRA,96752500,98314547,99876594,101438641,103000688,104562735,106124782,107686829,109248876,110810925,112372972,113935019
15,MANIPUR,2294480,2337207,2379934,2422661,2465388,2508115,2550842,2593569,2636296,2679029,2721756,2764483
16,MEGHALAYA,2306540,2372286,2438032,2503778,2569524,2635270,2701016,2766762,2832508,2898261,2964007,3029753
17,MIZORAM,889690,909822,929954,950086,970218,990350,1010482,1030614,1050746,1070882,1091014,1111146
18,NAGALAND,1990275,1989307,1988339,1987371,1986403,1985435,1984467,1983499,1982531,1981570,1980602,1979634
19,ODISHA,36707900,37231845,37755790,38279735,38803680,39327625,39851570,40375515,40899460,41423413,41947358,42471303
20,PUNJAB,24289130,24630640,24972150,25313660,25655170,25996680,26338190,26679700,27021210,27362726,27704236,28045746
21,RAJASTHAN,56473300,57688071,58902842,60117613,61332384,62547155,63761926,64976697,66191468,67406241,68621012,69835783
22,SIKKIM,541902,548480,555058,561636,568214,574792,581370,587948,594526,601110,607688,614266
23,TAMIL NADU,62111390,63114146,64116902,65119658,66122414,67125170,68127926,69130682,70133438,71136202,72138958,73141714
24,TRIPURA,3191880,3239795,3287710,3335625,3383540,3431455,3479370,3527285,3575200,3623117,3671032,3718947
25,UTTAR PRADESH,166053600,169406387,172759174,176111961,179464748,182817535,186170322,189523109,192875896,196228690,199581477,202934264
26,UTTARAKHAND,8489100,8651865,8814630,8977395,9140160,9302925,9465690,9628455,9791220,9953987,10116752,10279517
27,WEST BENGAL,80221300,81333943,82446586,83559229,84671872,85784515,86897158,88009801,89122444,90235093,91347736,92460379
28,A & N ISLANDS,356650,358979,361308,363637,365966,368295,370624,372953,375282,377615,379944,382273
29,CHANDIGARH,901080,916440,931800,947160,962520,977880,993240,1008600,1023960,1039326,1054686,1070046
30,D & N HAVELI,220963,233152,245341,257530,269719,281908,294097,306286,318475,330664,342853,355042
31,DAMAN & DIU,158080,166563,175046,183529,192012,200495,208978,217461,225944,234428,242911,251394
32,DELHI UT,13851503,14141676,14431849,14722022,15012195,15302368,15592541,15882714,16172887,16463062,16753235,17043408
33,LAKSHADWEEP,61300,61612,61924,62236,62548,62860,63172,63484,63796,64117,64429,64741
34,PUDUCHERRY,974820,1001784,1028748,1055712,1082676,1109640,1136604,1163568,1190532,1217500,1244464,1271428

Columns are re-arranged sucessfully.

In [11]:
#data is collected from : https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_literacy_rate

literacy_2001=[60.47,54.34,63.25,47.00,64.66,82.01,69.14,67.91,76.48,55.52,53.56,66.06,90.86,63.74,76.84,70.50,62.56,88.80,66.59,63.08,69.65,60.41,68.81,73.45,73.19,56.27,71.62,68.64,81.30,81.94,57.63,78.18,81.67,86.66,81.24]

literacy_2011=[67.02,65.38,72.19,61.80,70.28,88.70,78.03,75.55,82.80,67.16,66.41,75.36,94.00,69.32,82.34,76.94,74.43,91.33,79.55,72.87,75.84,66.11,81.42,80.33,80.09,67.68,78.82,76.26,86.63,86.05,76.24,87.10,86.21,91.85,85.85]

In [12]:
d1 = pd.DataFrame() #creating new empty data frame

d1['S/UT']=df['STATE/UT']#loading 'STATE/UT' column from 'df' data frame

d1['literacy_2001']=literacy_2001 #creating new column 'literacy_2001' with data of 'literacy_2001' list

d1['literacy_2011']=literacy_2011 #creating new column 'literacy_2011' with data of 'literacy_2011' list

d1

                 S/UT  literacy_2001  literacy_2011
0      ANDHRA PRADESH          60.47          67.02
1   ARUNACHAL PRADESH          54.34          65.38
2               ASSAM          63.25          72.19
3               BIHAR          47.00          61.80
4        CHHATTISGARH          64.66          70.28
5                 GOA          82.01          88.70
6             GUJARAT          69.14          78.03
7             HARYANA          67.91          75.55
8    HIMACHAL PRADESH          76.48          82.80
9     JAMMU & KASHMIR          55.52          67.16
10          JHARKHAND          53.56          66.41
11          KARNATAKA          66.06          75.36
12             KERALA          90.86          94.00
13     MADHYA PRADESH          63.74          69.32
14        MAHARASHTRA          76.84          82.34
15            MANIPUR          70.50          76.94
16          MEGHALAYA          62.56          74.43
17            MIZORAM          88.80          91.33
18           NAGALAND          66.59          79.55
19             ODISHA          63.08          72.87
20             PUNJAB          69.65          75.84
21          RAJASTHAN          60.41          66.11
22             SIKKIM          68.81          81.42
23         TAMIL NADU          73.45          80.33
24            TRIPURA          73.19          80.09
25      UTTAR PRADESH          56.27          67.68
26        UTTARAKHAND          71.62          78.82
27        WEST BENGAL          68.64          76.26
28      A & N ISLANDS          81.30          86.63
29         CHANDIGARH          81.94          86.05
30       D & N HAVELI          57.63          76.24
31        DAMAN & DIU          78.18          87.10
32           DELHI UT          81.67          86.21
33        LAKSHADWEEP          86.66          91.85
34         PUDUCHERRY          81.24          85.85

Data is inserted successfully.

According to the census, **data is only available** for the years **2001 and 2011.** Therefore, we can make **assumptions** for the **remaining years** by estimating **average literacy growth.**

In [13]:
#creating empty lists
literacy_2002=[]
literacy_2003=[]
literacy_2004=[]
literacy_2005=[]
literacy_2006=[]
literacy_2007=[]
literacy_2008=[]
literacy_2009=[]
literacy_2010=[]
literacy_2012=[]

for i in range(0,35):#running loop for 35 times
    
    l_2011=d1.iloc[i,-1] #storing literacy rate of 2011 year
    
    l_2001=d1.iloc[i,-2] #storing literacy rate of 2001 year
    
    diff=l_2011-l_2001 #calculating difference
    
    avg=diff/10 #calculating average
    
    literacy_2002.append(round(l_2001+avg,2)) #appending rounded off value of sum of 'l_2001' and 'avg'

    literacy_2003.append(round(literacy_2002[i]+avg,2)) #appending rounded off value of sum of 'literacy_2002' and 'avg'

    literacy_2004.append(round(literacy_2003[i]+avg,2)) #appending rounded off value of sum of 'literacy_2003' and 'avg'

    literacy_2005.append(round(literacy_2004[i]+avg,2)) #appending rounded off value of sum of 'literacy_2004' and 'avg'

    literacy_2006.append(round(literacy_2005[i]+avg,2)) #appending rounded off value of sum of 'literacy_2005' and 'avg'

    literacy_2007.append(round(literacy_2006[i]+avg,2)) #appending rounded off value of sum of 'literacy_2006' and 'avg'

    literacy_2008.append(round(literacy_2007[i]+avg,2)) #appending rounded off value of sum of 'literacy_2007' and 'avg'

    literacy_2009.append(round(literacy_2008[i]+avg,2)) #appending rounded off value of sum of 'literacy_2008' and 'avg'

    literacy_2010.append(round(literacy_2009[i]+avg,2)) #appending rounded off value of sum of 'literacy_2009' and 'avg'

    literacy_2012.append(round(l_2011+avg,2)) #appending rounded off value of sum of 'l_2011' and 'avg'
    

df['literacy_2001']=literacy_2001 #inserting data of 'literacy_2001' in 'df' data frame

df['literacy_2002']=literacy_2002 #inserting data of 'literacy_2002' in 'df' data frame

df['literacy_2003']=literacy_2003 #inserting data of 'literacy_2003' in 'df' data frame

df['literacy_2004']=literacy_2004 #inserting data of 'literacy_2004' in 'df' data frame

df['literacy_2005']=literacy_2005 #inserting data of 'literacy_2005' in 'df' data frame

df['literacy_2006']=literacy_2006 #inserting data of 'literacy_2006' in 'df' data frame

df['literacy_2007']=literacy_2007 #inserting data of 'literacy_2007' in 'df' data frame

df['literacy_2008']=literacy_2008 #inserting data of 'literacy_2008' in 'df' data frame

df['literacy_2009']=literacy_2009 #inserting data of 'literacy_2009' in 'df' data frame

df['literacy_2010']=literacy_2010 #inserting data of 'literacy_2010' in 'df' data frame

df['literacy_2011']=literacy_2011 #inserting data of 'literacy_2011' in 'df' data frame

df['literacy_2012']=literacy_2012 #inserting data of 'literacy_2012' in 'df' data frame

df

,STATE/UT,population_2001,population_2002,population_2003,population_2004,population_2005,population_2006,population_2007,population_2008,population_2009,...,literacy_2003,literacy_2004,literacy_2005,literacy_2006,literacy_2007,literacy_2008,literacy_2009,literacy_2010,literacy_2011,literacy_2012
0,ANDHRA PRADESH,75728400,73094239,70460078,67825917,65191756,62557595,59923434,57289273,54655112,...,61.78,62.44,63.10,63.76,64.41,65.06,65.72,66.38,67.02,67.68
1,ARUNACHAL PRADESH,1098328,1126756,1155184,1183612,1212040,1240468,1268896,1297324,1325752,...,56.54,57.64,58.74,59.84,60.94,62.04,63.14,64.24,65.38,66.48
2,ASSAM,26638600,27091667,27544734,27997801,28450868,28903935,29357002,29810069,30263136,...,65.03,65.92,66.81,67.70,68.59,69.48,70.37,71.26,72.19,73.08
3,BIHAR,82879910,84972382,87064854,89157326,91249798,93342270,95434742,97527214,99619686,...,49.96,51.44,52.92,54.40,55.88,57.36,58.84,60.32,61.80,63.28
4,CHHATTISGARH,20834530,21305096,21775662,22246228,22716794,23187360,23657926,24128492,24599058,...,65.78,66.34,66.90,67.46,68.02,68.58,69.14,69.70,70.28,70.84
5,GOA,1348900,1359782,1370664,1381546,1392428,1403310,1414192,1425074,1435956,...,83.35,84.02,84.69,85.36,86.03,86.70,87.37,88.04,88.70,89.37
6,GUJARAT,50597200,51575842,52554484,53533126,54511768,55490410,56469052,57447694,58426336,...,70.92,71.81,72.70,73.59,74.48,75.37,76.26,77.15,78.03,78.92
7,HARYANA,21083900,21550818,22017736,22484654,22951572,23418490,23885408,24352326,24819244,...,69.43,70.19,70.95,71.71,72.47,73.23,73.99,74.75,75.55,76.31
8,HIMACHAL PRADESH,6077453,6155358,6233263,6311168,6389073,6466978,6544883,6622788,6700693,...,77.74,78.37,79.00,79.63,80.26,80.89,81.52,82.15,82.80,83.43
9,JAMMU & KASHMIR,10070300,10318162,10566024,10813886,11061748,11309610,11557472,11805334,12053196,...,57.84,59.00,60.16,61.32,62.48,63.64,64.80,65.96,67.16,68.32
10,JHARKHAND,26946070,27550276,28154482,28758688,29362894,29967100,30571306,31175512,31779718,...,56.12,57.40,58.68,59.96,61.24,62.52,63.80,65.08,66.41,67.69
11,KARNATAKA,52734986,53574557,54414128,55253699,56093270,56932841,57772412,58611983,59451554,...,67.92,68.85,69.78,70.71,71.64,72.57,73.50,74.43,75.36,76.29
12,KERALA,31839000,31993867,32148734,32303601,32458468,32613335,32768202,32923069,33077936,...,91.48,91.79,92.10,92.41,92.72,93.03,93.34,93.65,94.00,94.31
13,MADHYA PRADESH,60385090,61606337,62827584,64048831,65270078,66491325,67712572,68933819,70155066,...,64.86,65.42,65.98,66.54,67.10,67.66,68.22,68.78,69.32,69.88
14,MAHARASHTRA,96752500,98314547,99876594,101438641,103000688,104562735,106124782,107686829,109248876,...,77.94,78.49,79.04,79.59,80.14,80.69,81.24,81.79,82.34,82.89
15,MANIPUR,2294480,2337207,2379934,2422661,2465388,2508115,2550842,2593569,2636296,...,71.78,72.42,73.06,73.70,74.34,74.98,75.62,76.26,76.94,77.58
16,MEGHALAYA,2306540,2372286,2438032,2503778,2569524,2635270,2701016,2766762,2832508,...,64.94,66.13,67.32,68.51,69.70,70.89,72.08,73.27,74.43,75.62
17,MIZORAM,889690,909822,929954,950086,970218,990350,1010482,1030614,1050746,...,89.30,89.55,89.80,90.05,90.30,90.55,90.80,91.05,91.33,91.58
18,NAGALAND,1990275,1989307,1988339,1987371,1986403,1985435,1984467,1983499,1982531,...,69.19,70.49,71.79,73.09,74.39,75.69,76.99,78.29,79.55,80.85
19,ODISHA,36707900,37231845,37755790,38279735,38803680,39327625,39851570,40375515,40899460,...,65.04,66.02,67.00,67.98,68.96,69.94,70.92,71.90,72.87,73.85
20,PUNJAB,24289130,24630640,24972150,25313660,25655170,25996680,26338190,26679700,27021210,...,70.89,71.51,72.13,72.75,73.37,73.99,74.61,75.23,75.84,76.46
21,RAJASTHAN,56473300,57688071,58902842,60117613,61332384,62547155,63761926,64976697,66191468,...,61.55,62.12,62.69,63.26,63.83,64.40,64.97,65.54,66.11,66.68
22,SIKKIM,541902,548480,555058,561636,568214,574792,581370,587948,594526,...,71.33,72.59,73.85,75.11,76.37,77.63,78.89,80.15,81.42,82.68
23,TAMIL NADU,62111390,63114146,64116902,65119658,66122414,67125170,68127926,69130682,70133438,...,74.83,75.52,76.21,76.90,77.59,78.28,78.97,79.66,80.33,81.02
24,TRIPURA,3191880,3239795,3287710,3335625,3383540,3431455,3479370,3527285,3575200,...,74.57,75.26,75.95,76.64,77.33,78.02,78.71,79.40,80.09,80.78
25,UTTAR PRADESH,166053600,169406387,172759174,176111961,179464748,182817535,186170322,189523109,192875896,...,58.55,59.69,60.83,61.97,63.11,64.25,65.39,66.53,67.68,68.82
26,UTTARAKHAND,8489100,8651865,8814630,8977395,9140160,9302925,9465690,9628455,9791220,...,73.06,73.78,74.50,75.22,75.94,76.66,77.38,78.10,78.82,79.54
27,WEST BENGAL,80221300,81333943,82446586,83559229,84671872,85784515,86897158,88009801,89122444,...,70.16,70.92,71.68,72.44,73.20,73.96,74.72,75.48,76.26,77.02
28,A & N ISLANDS,356650,358979,361308,363637,365966,368295,370624,372953,375282,...,82.36,82.89,83.42,83.95,84.48,85.01,85.54,86.07,86.63,87.16
29,CHANDIGARH,901080,916440,931800,947160,962520,977880,993240,1008600,1023960,...,82.76,83.17,83.58,83.99,84.40,84.81,85.22,85.63,86.05,86.46
30,D & N HAVELI,220963,233152,245341,257530,269719,281908,294097,306286,318475,...,61.35,63.21,65.07,66.93,68.79,70.65,72.51,74.37,76.24,78.10
31,DAMAN & DIU,158080,166563,175046,183529,192012,200495,208978,217461,225944,...,79.96,80.85,81.74,82.63,83.52,84.41,85.30,86.19,87.10,87.99
32,DELHI UT,13851503,14141676,14431849,14722022,15012195,15302368,15592541,15882714,16172887,...,82.57,83.02,83.47,83.92,84.37,84.82,85.27,85.72,86.21,86.66
33,LAKSHADWEEP,61300,61612,61924,62236,62548,62860,63172,63484,63796,...,87.70,88.22,88.74,89.26,89.78,90.30,90.82,91.34,91.85,92.37
34,PUDUCHERRY,974820,1001784,1028748,1055712,1082676,1109640,1136604,1163568,1190532,...,82.16,82.62,83.08,83.54,84.00,84.46,84.92,85.38,85.85,86.31

Data is inserted successfully.

In [14]:
#data is collected from : https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_literacy_rate

#data of 'DADRA & NAGAR HAVELI' is collected from : https://dnh.gov.in/ 

#data of 'Daman and Diu' is collected from : https://en.wikipedia.org/wiki/Daman_and_Diu

area=[162975, 83743, 78438, 94163, 135192, 3702, 196024, 44212, 55673, 55538, 79716, 191791, 38863, 308252, 307713, 22327, 22429, 21081, 16579, 155707, 50362, 342239, 7096, 130058, 10491, 240928, 53483, 88752, 8249, 114, 491, 112, 1484, 32, 479]

df['Area (Km²)']=area #creating new column for area of each state

df

,STATE/UT,population_2001,population_2002,population_2003,population_2004,population_2005,population_2006,population_2007,population_2008,population_2009,...,literacy_2004,literacy_2005,literacy_2006,literacy_2007,literacy_2008,literacy_2009,literacy_2010,literacy_2011,literacy_2012,Area (Km²)
0,ANDHRA PRADESH,75728400,73094239,70460078,67825917,65191756,62557595,59923434,57289273,54655112,...,62.44,63.10,63.76,64.41,65.06,65.72,66.38,67.02,67.68,162975
1,ARUNACHAL PRADESH,1098328,1126756,1155184,1183612,1212040,1240468,1268896,1297324,1325752,...,57.64,58.74,59.84,60.94,62.04,63.14,64.24,65.38,66.48,83743
2,ASSAM,26638600,27091667,27544734,27997801,28450868,28903935,29357002,29810069,30263136,...,65.92,66.81,67.70,68.59,69.48,70.37,71.26,72.19,73.08,78438
3,BIHAR,82879910,84972382,87064854,89157326,91249798,93342270,95434742,97527214,99619686,...,51.44,52.92,54.40,55.88,57.36,58.84,60.32,61.80,63.28,94163
4,CHHATTISGARH,20834530,21305096,21775662,22246228,22716794,23187360,23657926,24128492,24599058,...,66.34,66.90,67.46,68.02,68.58,69.14,69.70,70.28,70.84,135192
5,GOA,1348900,1359782,1370664,1381546,1392428,1403310,1414192,1425074,1435956,...,84.02,84.69,85.36,86.03,86.70,87.37,88.04,88.70,89.37,3702
6,GUJARAT,50597200,51575842,52554484,53533126,54511768,55490410,56469052,57447694,58426336,...,71.81,72.70,73.59,74.48,75.37,76.26,77.15,78.03,78.92,196024
7,HARYANA,21083900,21550818,22017736,22484654,22951572,23418490,23885408,24352326,24819244,...,70.19,70.95,71.71,72.47,73.23,73.99,74.75,75.55,76.31,44212
8,HIMACHAL PRADESH,6077453,6155358,6233263,6311168,6389073,6466978,6544883,6622788,6700693,...,78.37,79.00,79.63,80.26,80.89,81.52,82.15,82.80,83.43,55673
9,JAMMU & KASHMIR,10070300,10318162,10566024,10813886,11061748,11309610,11557472,11805334,12053196,...,59.00,60.16,61.32,62.48,63.64,64.80,65.96,67.16,68.32,55538
10,JHARKHAND,26946070,27550276,28154482,28758688,29362894,29967100,30571306,31175512,31779718,...,57.40,58.68,59.96,61.24,62.52,63.80,65.08,66.41,67.69,79716
11,KARNATAKA,52734986,53574557,54414128,55253699,56093270,56932841,57772412,58611983,59451554,...,68.85,69.78,70.71,71.64,72.57,73.50,74.43,75.36,76.29,191791
12,KERALA,31839000,31993867,32148734,32303601,32458468,32613335,32768202,32923069,33077936,...,91.79,92.10,92.41,92.72,93.03,93.34,93.65,94.00,94.31,38863
13,MADHYA PRADESH,60385090,61606337,62827584,64048831,65270078,66491325,67712572,68933819,70155066,...,65.42,65.98,66.54,67.10,67.66,68.22,68.78,69.32,69.88,308252
14,MAHARASHTRA,96752500,98314547,99876594,101438641,103000688,104562735,106124782,107686829,109248876,...,78.49,79.04,79.59,80.14,80.69,81.24,81.79,82.34,82.89,307713
15,MANIPUR,2294480,2337207,2379934,2422661,2465388,2508115,2550842,2593569,2636296,...,72.42,73.06,73.70,74.34,74.98,75.62,76.26,76.94,77.58,22327
16,MEGHALAYA,2306540,2372286,2438032,2503778,2569524,2635270,2701016,2766762,2832508,...,66.13,67.32,68.51,69.70,70.89,72.08,73.27,74.43,75.62,22429
17,MIZORAM,889690,909822,929954,950086,970218,990350,1010482,1030614,1050746,...,89.55,89.80,90.05,90.30,90.55,90.80,91.05,91.33,91.58,21081
18,NAGALAND,1990275,1989307,1988339,1987371,1986403,1985435,1984467,1983499,1982531,...,70.49,71.79,73.09,74.39,75.69,76.99,78.29,79.55,80.85,16579
19,ODISHA,36707900,37231845,37755790,38279735,38803680,39327625,39851570,40375515,40899460,...,66.02,67.00,67.98,68.96,69.94,70.92,71.90,72.87,73.85,155707
20,PUNJAB,24289130,24630640,24972150,25313660,25655170,25996680,26338190,26679700,27021210,...,71.51,72.13,72.75,73.37,73.99,74.61,75.23,75.84,76.46,50362
21,RAJASTHAN,56473300,57688071,58902842,60117613,61332384,62547155,63761926,64976697,66191468,...,62.12,62.69,63.26,63.83,64.40,64.97,65.54,66.11,66.68,342239
22,SIKKIM,541902,548480,555058,561636,568214,574792,581370,587948,594526,...,72.59,73.85,75.11,76.37,77.63,78.89,80.15,81.42,82.68,7096
23,TAMIL NADU,62111390,63114146,64116902,65119658,66122414,67125170,68127926,69130682,70133438,...,75.52,76.21,76.90,77.59,78.28,78.97,79.66,80.33,81.02,130058
24,TRIPURA,3191880,3239795,3287710,3335625,3383540,3431455,3479370,3527285,3575200,...,75.26,75.95,76.64,77.33,78.02,78.71,79.40,80.09,80.78,10491
25,UTTAR PRADESH,166053600,169406387,172759174,176111961,179464748,182817535,186170322,189523109,192875896,...,59.69,60.83,61.97,63.11,64.25,65.39,66.53,67.68,68.82,240928
26,UTTARAKHAND,8489100,8651865,8814630,8977395,9140160,9302925,9465690,9628455,9791220,...,73.78,74.50,75.22,75.94,76.66,77.38,78.10,78.82,79.54,53483
27,WEST BENGAL,80221300,81333943,82446586,83559229,84671872,85784515,86897158,88009801,89122444,...,70.92,71.68,72.44,73.20,73.96,74.72,75.48,76.26,77.02,88752
28,A & N ISLANDS,356650,358979,361308,363637,365966,368295,370624,372953,375282,...,82.89,83.42,83.95,84.48,85.01,85.54,86.07,86.63,87.16,8249
29,CHANDIGARH,901080,916440,931800,947160,962520,977880,993240,1008600,1023960,...,83.17,83.58,83.99,84.40,84.81,85.22,85.63,86.05,86.46,114
30,D & N HAVELI,220963,233152,245341,257530,269719,281908,294097,306286,318475,...,63.21,65.07,66.93,68.79,70.65,72.51,74.37,76.24,78.10,491
31,DAMAN & DIU,158080,166563,175046,183529,192012,200495,208978,217461,225944,...,80.85,81.74,82.63,83.52,84.41,85.30,86.19,87.10,87.99,112
32,DELHI UT,13851503,14141676,14431849,14722022,15012195,15302368,15592541,15882714,16172887,...,83.02,83.47,83.92,84.37,84.82,85.27,85.72,86.21,86.66,1484
33,LAKSHADWEEP,61300,61612,61924,62236,62548,62860,63172,63484,63796,...,88.22,88.74,89.26,89.78,90.30,90.82,91.34,91.85,92.37,32
34,PUDUCHERRY,974820,1001784,1028748,1055712,1082676,1109640,1136604,1163568,1190532,...,82.62,83.08,83.54,84.00,84.46,84.92,85.38,85.85,86.31,479

In [15]:
#selecting 'STATE/UT' and 'Total IPC CRIMES' columns from 'a' dataframe
totalcrime=a[['STATE/UT','DISTRICT','TOTAL IPC CRIMES']]
totalcrime

            STATE/UT       DISTRICT  TOTAL IPC CRIMES
0     ANDHRA PRADESH       ADILABAD              4154
1     ANDHRA PRADESH      ANANTAPUR              4125
2     ANDHRA PRADESH       CHITTOOR              5818
3     ANDHRA PRADESH       CUDDAPAH              3140
4     ANDHRA PRADESH  EAST GODAVARI              6507
...              ...            ...               ...
9012     LAKSHADWEEP    LAKSHADWEEP                60
9013     LAKSHADWEEP          TOTAL                60
9014      PUDUCHERRY       KARAIKAL               787
9015      PUDUCHERRY     PUDUCHERRY              3494
9016      PUDUCHERRY          TOTAL              4281

[9017 rows x 3 columns]

As the **'TOTAL IPC CRIMES'** column is **district-wise**, we can **add all crimes** in **corresponding district** and **assign** them **according** to the **'STATE/UT'.**

In [16]:
#filtering the DataFrame based on the 'TOTAL' value in the 'DISTRICT' column, as it represents the total value for the remaining districts.
totalcrime=totalcrime[totalcrime['DISTRICT']=='TOTAL']

totalcrime=totalcrime.groupby('STATE/UT')['TOTAL IPC CRIMES'].sum()#adding values to the corresponding 'STATE/UT'
totalcrime

STATE/UT
A & N ISLANDS           9102
ANDHRA PRADESH       2018981
ARUNACHAL PRADESH      27652
ASSAM                 597764
BIHAR                1346293
CHANDIGARH             40807
CHHATTISGARH          561027
D & N HAVELI            4651
DAMAN & DIU             2948
GOA                    32051
GUJARAT              1385775
HARYANA               595303
HIMACHAL PRADESH      154948
JAMMU & KASHMIR       259155
JHARKHAND             422351
KARNATAKA            1481063
KERALA               1437459
LAKSHADWEEP              743
MADHYA PRADESH       2413770
MAHARASHTRA          2273436
MANIPUR                35072
MEGHALAYA              25249
MIZORAM                26146
NAGALAND               13133
ODISHA                647946
PUDUCHERRY             54116
PUNJAB                384131
RAJASTHAN            1855916
SIKKIM                  7000
TAMIL NADU           2060176
TRIPURA                52734
UTTAR PRADESH        1858074
UTTARAKHAND           103204
WEST BENGAL          1119304
Name: TOTAL IPC CRIMES, dtype: int64

Theese are the total crimes of each state/ut.

In [17]:
#merging data based on 'STATE/UT'
df=pd.merge(df,totalcrime,on='STATE/UT')
df

,STATE/UT,population_2001,population_2002,population_2003,population_2004,population_2005,population_2006,population_2007,population_2008,population_2009,...,literacy_2005,literacy_2006,literacy_2007,literacy_2008,literacy_2009,literacy_2010,literacy_2011,literacy_2012,Area (Km²),TOTAL IPC CRIMES
0,ANDHRA PRADESH,75728400,73094239,70460078,67825917,65191756,62557595,59923434,57289273,54655112,...,63.10,63.76,64.41,65.06,65.72,66.38,67.02,67.68,162975,2018981
1,ARUNACHAL PRADESH,1098328,1126756,1155184,1183612,1212040,1240468,1268896,1297324,1325752,...,58.74,59.84,60.94,62.04,63.14,64.24,65.38,66.48,83743,27652
2,ASSAM,26638600,27091667,27544734,27997801,28450868,28903935,29357002,29810069,30263136,...,66.81,67.70,68.59,69.48,70.37,71.26,72.19,73.08,78438,597764
3,BIHAR,82879910,84972382,87064854,89157326,91249798,93342270,95434742,97527214,99619686,...,52.92,54.40,55.88,57.36,58.84,60.32,61.80,63.28,94163,1346293
4,CHHATTISGARH,20834530,21305096,21775662,22246228,22716794,23187360,23657926,24128492,24599058,...,66.90,67.46,68.02,68.58,69.14,69.70,70.28,70.84,135192,561027
5,GOA,1348900,1359782,1370664,1381546,1392428,1403310,1414192,1425074,1435956,...,84.69,85.36,86.03,86.70,87.37,88.04,88.70,89.37,3702,32051
6,GUJARAT,50597200,51575842,52554484,53533126,54511768,55490410,56469052,57447694,58426336,...,72.70,73.59,74.48,75.37,76.26,77.15,78.03,78.92,196024,1385775
7,HARYANA,21083900,21550818,22017736,22484654,22951572,23418490,23885408,24352326,24819244,...,70.95,71.71,72.47,73.23,73.99,74.75,75.55,76.31,44212,595303
8,HIMACHAL PRADESH,6077453,6155358,6233263,6311168,6389073,6466978,6544883,6622788,6700693,...,79.00,79.63,80.26,80.89,81.52,82.15,82.80,83.43,55673,154948
9,JAMMU & KASHMIR,10070300,10318162,10566024,10813886,11061748,11309610,11557472,11805334,12053196,...,60.16,61.32,62.48,63.64,64.80,65.96,67.16,68.32,55538,259155
10,JHARKHAND,26946070,27550276,28154482,28758688,29362894,29967100,30571306,31175512,31779718,...,58.68,59.96,61.24,62.52,63.80,65.08,66.41,67.69,79716,422351
11,KARNATAKA,52734986,53574557,54414128,55253699,56093270,56932841,57772412,58611983,59451554,...,69.78,70.71,71.64,72.57,73.50,74.43,75.36,76.29,191791,1481063
12,KERALA,31839000,31993867,32148734,32303601,32458468,32613335,32768202,32923069,33077936,...,92.10,92.41,92.72,93.03,93.34,93.65,94.00,94.31,38863,1437459
13,MADHYA PRADESH,60385090,61606337,62827584,64048831,65270078,66491325,67712572,68933819,70155066,...,65.98,66.54,67.10,67.66,68.22,68.78,69.32,69.88,308252,2413770
14,MAHARASHTRA,96752500,98314547,99876594,101438641,103000688,104562735,106124782,107686829,109248876,...,79.04,79.59,80.14,80.69,81.24,81.79,82.34,82.89,307713,2273436
15,MANIPUR,2294480,2337207,2379934,2422661,2465388,2508115,2550842,2593569,2636296,...,73.06,73.70,74.34,74.98,75.62,76.26,76.94,77.58,22327,35072
16,MEGHALAYA,2306540,2372286,2438032,2503778,2569524,2635270,2701016,2766762,2832508,...,67.32,68.51,69.70,70.89,72.08,73.27,74.43,75.62,22429,25249
17,MIZORAM,889690,909822,929954,950086,970218,990350,1010482,1030614,1050746,...,89.80,90.05,90.30,90.55,90.80,91.05,91.33,91.58,21081,26146
18,NAGALAND,1990275,1989307,1988339,1987371,1986403,1985435,1984467,1983499,1982531,...,71.79,73.09,74.39,75.69,76.99,78.29,79.55,80.85,16579,13133
19,ODISHA,36707900,37231845,37755790,38279735,38803680,39327625,39851570,40375515,40899460,...,67.00,67.98,68.96,69.94,70.92,71.90,72.87,73.85,155707,647946
20,PUNJAB,24289130,24630640,24972150,25313660,25655170,25996680,26338190,26679700,27021210,...,72.13,72.75,73.37,73.99,74.61,75.23,75.84,76.46,50362,384131
21,RAJASTHAN,56473300,57688071,58902842,60117613,61332384,62547155,63761926,64976697,66191468,...,62.69,63.26,63.83,64.40,64.97,65.54,66.11,66.68,342239,1855916
22,SIKKIM,541902,548480,555058,561636,568214,574792,581370,587948,594526,...,73.85,75.11,76.37,77.63,78.89,80.15,81.42,82.68,7096,7000
23,TAMIL NADU,62111390,63114146,64116902,65119658,66122414,67125170,68127926,69130682,70133438,...,76.21,76.90,77.59,78.28,78.97,79.66,80.33,81.02,130058,2060176
24,TRIPURA,3191880,3239795,3287710,3335625,3383540,3431455,3479370,3527285,3575200,...,75.95,76.64,77.33,78.02,78.71,79.40,80.09,80.78,10491,52734
25,UTTAR PRADESH,166053600,169406387,172759174,176111961,179464748,182817535,186170322,189523109,192875896,...,60.83,61.97,63.11,64.25,65.39,66.53,67.68,68.82,240928,1858074
26,UTTARAKHAND,8489100,8651865,8814630,8977395,9140160,9302925,9465690,9628455,9791220,...,74.50,75.22,75.94,76.66,77.38,78.10,78.82,79.54,53483,103204
27,WEST BENGAL,80221300,81333943,82446586,83559229,84671872,85784515,86897158,88009801,89122444,...,71.68,72.44,73.20,73.96,74.72,75.48,76.26,77.02,88752,1119304
28,A & N ISLANDS,356650,358979,361308,363637,365966,368295,370624,372953,375282,...,83.42,83.95,84.48,85.01,85.54,86.07,86.63,87.16,8249,9102
29,CHANDIGARH,901080,916440,931800,947160,962520,977880,993240,1008600,1023960,...,83.58,83.99,84.40,84.81,85.22,85.63,86.05,86.46,114,40807
30,D & N HAVELI,220963,233152,245341,257530,269719,281908,294097,306286,318475,...,65.07,66.93,68.79,70.65,72.51,74.37,76.24,78.10,491,4651
31,DAMAN & DIU,158080,166563,175046,183529,192012,200495,208978,217461,225944,...,81.74,82.63,83.52,84.41,85.30,86.19,87.10,87.99,112,2948
32,LAKSHADWEEP,61300,61612,61924,62236,62548,62860,63172,63484,63796,...,88.74,89.26,89.78,90.30,90.82,91.34,91.85,92.37,32,743
33,PUDUCHERRY,974820,1001784,1028748,1055712,1082676,1109640,1136604,1163568,1190532,...,83.08,83.54,84.00,84.46,84.92,85.38,85.85,86.31,479,54116

***'Total IPC Crimes' column is added successfully.***

In [18]:
#selecting all columns except for 'YEAR','OTHER IPC CRIMES' and 'TOTAL IPC CRIMES' columns  from 'a' data frame
selected_columns=a.drop(['YEAR','OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],axis=1)

#filtering the DataFrame based on the 'TOTAL' value in the 'DISTRICT' column, as it represents the total value for the remaining districts.
selected_columns=selected_columns[selected_columns['DISTRICT']=='TOTAL']

In [19]:
crime=pd.DataFrame()#creating empty data frame

columns=selected_columns.columns.to_list()#storing columns of 'selected_columns' as a list

#removing unwanted columns
columns.remove('STATE/UT')
columns.remove('DISTRICT')

for i in columns:#iterating through 'columns'
    
    crime[i]=selected_columns.groupby('STATE/UT')[i].sum()#creating new column in 'crime' and adding all values present in 'i' column


crime.reset_index(inplace=True)#reseting index 
crime

,STATE/UT,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,...,CHEATING,COUNTERFIETING,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE
0,A & N ISLANDS,160,65,21,109,0,109,94,77,17,...,253,11,98,1105,6,214,43,121,0,42
1,ANDHRA PRADESH,31756,22420,1763,13479,2,13477,21239,14936,6303,...,98843,3107,11968,546565,6215,51999,36131,119007,17,138435
2,ARUNACHAL PRADESH,841,417,36,500,0,500,857,558,299,...,520,52,250,5157,2,784,18,167,0,745
3,ASSAM,15432,5662,718,16178,5,16173,27939,22920,5019,...,12391,898,7918,69183,1276,13620,112,39388,8,30205
4,BIHAR,41245,40919,3672,13124,2,13122,37220,19389,17831,...,30690,826,8509,189266,13548,7576,226,25680,440,44442
5,CHANDIGARH,243,301,79,281,0,281,640,534,106,...,2301,27,62,816,42,314,143,807,0,98
6,CHHATTISGARH,12060,7910,348,11838,0,11838,3345,2630,715,...,6998,578,3147,85026,1142,19165,1725,9573,5,25432
7,D & N HAVELI,108,31,3,56,0,56,141,94,47,...,171,14,55,318,1,50,4,38,0,148
8,DAMAN & DIU,68,38,2,20,0,20,31,15,16,...,73,30,34,190,3,15,2,35,0,311
9,GOA,487,269,67,350,0,350,236,164,72,...,1176,162,272,2287,19,328,123,191,0,2664
10,GUJARAT,13775,6112,430,4249,0,4249,15246,12918,2328,...,17066,2582,5647,135218,502,8998,1365,59431,0,54385
11,HARYANA,10471,7434,857,6410,1,6409,8656,6129,2527,...,15575,372,1906,51254,3130,5323,8188,27112,0,15197
12,HIMACHAL PRADESH,1454,835,130,1804,0,1804,1798,1541,257,...,2653,54,1484,15909,55,3597,439,3245,0,6309
13,JAMMU & KASHMIR,6304,10303,347,2810,0,2810,9665,8820,845,...,5463,318,3166,3883,135,11509,3993,1800,0,4524
14,JHARKHAND,19060,12270,1231,9159,5,9154,8476,5282,3194,...,9476,203,2012,40237,3291,3985,247,8409,145,13612
15,KARNATAKA,19937,18512,857,5174,2,5172,10029,5315,4714,...,46335,1563,3711,251332,2918,23699,831,30052,47,5078
16,KERALA,4733,5327,1897,7447,0,7447,2891,1898,993,...,43758,1093,5580,232451,301,31490,3304,46074,0,489
17,LAKSHADWEEP,3,6,0,7,0,7,1,1,0,...,0,1,22,57,0,5,0,7,0,0
18,MADHYA PRADESH,28399,29458,1834,36087,1,36086,11958,9243,2715,...,18495,424,10354,412577,9036,79878,9317,39969,60,64969
19,MAHARASHTRA,32767,20589,1409,17986,2,17984,15101,10853,4248,...,79902,3806,14515,353760,4249,39219,12110,80363,2,134613
20,MANIPUR,1955,3536,42,387,0,387,1811,1057,754,...,1231,91,952,3433,2,504,3,219,0,87
21,MEGHALAYA,1730,601,84,1020,0,1020,729,264,465,...,1015,88,443,1736,15,532,8,165,4,682
22,MIZORAM,403,258,67,826,1,825,96,10,86,...,743,121,267,1216,4,816,6,54,3,315
23,NAGALAND,1038,464,101,220,0,220,392,71,321,...,379,54,70,532,0,96,10,9,1,372
24,ODISHA,14453,15652,698,11430,0,11430,9729,8291,1438,...,13370,242,5280,75761,4555,29946,2939,18697,18,36507
25,PUDUCHERRY,357,343,78,77,0,77,169,121,48,...,564,32,190,10694,26,613,284,105,0,2602
26,PUNJAB,9493,10397,1558,5459,1,5458,7619,5385,2234,...,37936,743,907,56920,1546,4047,762,11998,2,33339
27,RAJASTHAN,15844,21342,889,15798,0,15798,30727,24671,6056,...,140800,726,8312,267353,5066,30853,354,100101,6,78350
28,SIKKIM,166,111,38,195,0,195,76,62,14,...,350,19,80,939,2,230,14,44,0,422
29,TAMIL NADU,20127,26597,343,6952,2,6950,15303,12436,2867,...,31689,2420,8149,280673,2317,19329,10043,18188,15,140193
30,TRIPURA,2022,681,19,2058,0,2058,1443,875,568,...,852,133,548,9306,314,2773,39,6514,0,1542
31,UTTAR PRADESH,65443,60520,17266,19058,2,19056,59266,47590,11676,...,83960,3224,4554,139750,23824,29698,26511,77617,3,113821
32,UTTARAKHAND,2948,2627,514,1378,0,1378,2852,2334,518,...,5610,263,314,10610,906,1545,1519,4142,1,6680
33,WEST BENGAL,21056,14693,6333,20787,0,20787,25999,21773,4226,...,30831,1921,2364,94152,5172,22871,1554,130668,114,37751

From this data frame, we can assess the **type of crime in each state** by **assigning** the **category** with the **highest value**.

In [20]:
selected_data=crime.drop('STATE/UT',axis=1)#dropping 'STATE/UT' column and storing remaining data 

type_c=[]#creating empty list

for i in range(0,34):#running loop for 34 times
    type_c.append(selected_data.iloc[i].idxmax())  #appending column to 'type_c' according to max value present in each row
    
#creating new data frame
type_of_crime=pd.DataFrame({'STATE/UT':crime['STATE/UT'],'TYPE OF CRIME':type_c})
type_of_crime

             STATE/UT       TYPE OF CRIME
0       A & N ISLANDS               THEFT
1      ANDHRA PRADESH  HURT/GREVIOUS HURT
2   ARUNACHAL PRADESH               THEFT
3               ASSAM               THEFT
4               BIHAR  HURT/GREVIOUS HURT
5          CHANDIGARH               THEFT
6        CHHATTISGARH  HURT/GREVIOUS HURT
7        D & N HAVELI               THEFT
8         DAMAN & DIU               THEFT
9                 GOA               THEFT
10            GUJARAT               THEFT
11            HARYANA               THEFT
12   HIMACHAL PRADESH  HURT/GREVIOUS HURT
13    JAMMU & KASHMIR               THEFT
14          JHARKHAND               THEFT
15          KARNATAKA  HURT/GREVIOUS HURT
16             KERALA  HURT/GREVIOUS HURT
17        LAKSHADWEEP               RIOTS
18     MADHYA PRADESH  HURT/GREVIOUS HURT
19        MAHARASHTRA               THEFT
20            MANIPUR               THEFT
21          MEGHALAYA               THEFT
22            MIZORAM               THEFT
23           NAGALAND               THEFT
24             ODISHA               THEFT
25         PUDUCHERRY  HURT/GREVIOUS HURT
26             PUNJAB  HURT/GREVIOUS HURT
27          RAJASTHAN  HURT/GREVIOUS HURT
28             SIKKIM               THEFT
29         TAMIL NADU  HURT/GREVIOUS HURT
30            TRIPURA  HURT/GREVIOUS HURT
31      UTTAR PRADESH               THEFT
32        UTTARAKHAND               THEFT
33        WEST BENGAL               THEFT

We can **merge this data frame** with **'df' data frame**.

In [21]:
df=pd.merge(df,type_of_crime,on='STATE/UT')
df

,STATE/UT,population_2001,population_2002,population_2003,population_2004,population_2005,population_2006,population_2007,population_2008,population_2009,...,literacy_2006,literacy_2007,literacy_2008,literacy_2009,literacy_2010,literacy_2011,literacy_2012,Area (Km²),TOTAL IPC CRIMES,TYPE OF CRIME
0,ANDHRA PRADESH,75728400,73094239,70460078,67825917,65191756,62557595,59923434,57289273,54655112,...,63.76,64.41,65.06,65.72,66.38,67.02,67.68,162975,2018981,HURT/GREVIOUS HURT
1,ARUNACHAL PRADESH,1098328,1126756,1155184,1183612,1212040,1240468,1268896,1297324,1325752,...,59.84,60.94,62.04,63.14,64.24,65.38,66.48,83743,27652,THEFT
2,ASSAM,26638600,27091667,27544734,27997801,28450868,28903935,29357002,29810069,30263136,...,67.70,68.59,69.48,70.37,71.26,72.19,73.08,78438,597764,THEFT
3,BIHAR,82879910,84972382,87064854,89157326,91249798,93342270,95434742,97527214,99619686,...,54.40,55.88,57.36,58.84,60.32,61.80,63.28,94163,1346293,HURT/GREVIOUS HURT
4,CHHATTISGARH,20834530,21305096,21775662,22246228,22716794,23187360,23657926,24128492,24599058,...,67.46,68.02,68.58,69.14,69.70,70.28,70.84,135192,561027,HURT/GREVIOUS HURT
5,GOA,1348900,1359782,1370664,1381546,1392428,1403310,1414192,1425074,1435956,...,85.36,86.03,86.70,87.37,88.04,88.70,89.37,3702,32051,THEFT
6,GUJARAT,50597200,51575842,52554484,53533126,54511768,55490410,56469052,57447694,58426336,...,73.59,74.48,75.37,76.26,77.15,78.03,78.92,196024,1385775,THEFT
7,HARYANA,21083900,21550818,22017736,22484654,22951572,23418490,23885408,24352326,24819244,...,71.71,72.47,73.23,73.99,74.75,75.55,76.31,44212,595303,THEFT
8,HIMACHAL PRADESH,6077453,6155358,6233263,6311168,6389073,6466978,6544883,6622788,6700693,...,79.63,80.26,80.89,81.52,82.15,82.80,83.43,55673,154948,HURT/GREVIOUS HURT
9,JAMMU & KASHMIR,10070300,10318162,10566024,10813886,11061748,11309610,11557472,11805334,12053196,...,61.32,62.48,63.64,64.80,65.96,67.16,68.32,55538,259155,THEFT
10,JHARKHAND,26946070,27550276,28154482,28758688,29362894,29967100,30571306,31175512,31779718,...,59.96,61.24,62.52,63.80,65.08,66.41,67.69,79716,422351,THEFT
11,KARNATAKA,52734986,53574557,54414128,55253699,56093270,56932841,57772412,58611983,59451554,...,70.71,71.64,72.57,73.50,74.43,75.36,76.29,191791,1481063,HURT/GREVIOUS HURT
12,KERALA,31839000,31993867,32148734,32303601,32458468,32613335,32768202,32923069,33077936,...,92.41,92.72,93.03,93.34,93.65,94.00,94.31,38863,1437459,HURT/GREVIOUS HURT
13,MADHYA PRADESH,60385090,61606337,62827584,64048831,65270078,66491325,67712572,68933819,70155066,...,66.54,67.10,67.66,68.22,68.78,69.32,69.88,308252,2413770,HURT/GREVIOUS HURT
14,MAHARASHTRA,96752500,98314547,99876594,101438641,103000688,104562735,106124782,107686829,109248876,...,79.59,80.14,80.69,81.24,81.79,82.34,82.89,307713,2273436,THEFT
15,MANIPUR,2294480,2337207,2379934,2422661,2465388,2508115,2550842,2593569,2636296,...,73.70,74.34,74.98,75.62,76.26,76.94,77.58,22327,35072,THEFT
16,MEGHALAYA,2306540,2372286,2438032,2503778,2569524,2635270,2701016,2766762,2832508,...,68.51,69.70,70.89,72.08,73.27,74.43,75.62,22429,25249,THEFT
17,MIZORAM,889690,909822,929954,950086,970218,990350,1010482,1030614,1050746,...,90.05,90.30,90.55,90.80,91.05,91.33,91.58,21081,26146,THEFT
18,NAGALAND,1990275,1989307,1988339,1987371,1986403,1985435,1984467,1983499,1982531,...,73.09,74.39,75.69,76.99,78.29,79.55,80.85,16579,13133,THEFT
19,ODISHA,36707900,37231845,37755790,38279735,38803680,39327625,39851570,40375515,40899460,...,67.98,68.96,69.94,70.92,71.90,72.87,73.85,155707,647946,THEFT
20,PUNJAB,24289130,24630640,24972150,25313660,25655170,25996680,26338190,26679700,27021210,...,72.75,73.37,73.99,74.61,75.23,75.84,76.46,50362,384131,HURT/GREVIOUS HURT
21,RAJASTHAN,56473300,57688071,58902842,60117613,61332384,62547155,63761926,64976697,66191468,...,63.26,63.83,64.40,64.97,65.54,66.11,66.68,342239,1855916,HURT/GREVIOUS HURT
22,SIKKIM,541902,548480,555058,561636,568214,574792,581370,587948,594526,...,75.11,76.37,77.63,78.89,80.15,81.42,82.68,7096,7000,THEFT
23,TAMIL NADU,62111390,63114146,64116902,65119658,66122414,67125170,68127926,69130682,70133438,...,76.90,77.59,78.28,78.97,79.66,80.33,81.02,130058,2060176,HURT/GREVIOUS HURT
24,TRIPURA,3191880,3239795,3287710,3335625,3383540,3431455,3479370,3527285,3575200,...,76.64,77.33,78.02,78.71,79.40,80.09,80.78,10491,52734,HURT/GREVIOUS HURT
25,UTTAR PRADESH,166053600,169406387,172759174,176111961,179464748,182817535,186170322,189523109,192875896,...,61.97,63.11,64.25,65.39,66.53,67.68,68.82,240928,1858074,THEFT
26,UTTARAKHAND,8489100,8651865,8814630,8977395,9140160,9302925,9465690,9628455,9791220,...,75.22,75.94,76.66,77.38,78.10,78.82,79.54,53483,103204,THEFT
27,WEST BENGAL,80221300,81333943,82446586,83559229,84671872,85784515,86897158,88009801,89122444,...,72.44,73.20,73.96,74.72,75.48,76.26,77.02,88752,1119304,THEFT
28,A & N ISLANDS,356650,358979,361308,363637,365966,368295,370624,372953,375282,...,83.95,84.48,85.01,85.54,86.07,86.63,87.16,8249,9102,THEFT
29,CHANDIGARH,901080,916440,931800,947160,962520,977880,993240,1008600,1023960,...,83.99,84.40,84.81,85.22,85.63,86.05,86.46,114,40807,THEFT
30,D & N HAVELI,220963,233152,245341,257530,269719,281908,294097,306286,318475,...,66.93,68.79,70.65,72.51,74.37,76.24,78.10,491,4651,THEFT
31,DAMAN & DIU,158080,166563,175046,183529,192012,200495,208978,217461,225944,...,82.63,83.52,84.41,85.30,86.19,87.10,87.99,112,2948,THEFT
32,LAKSHADWEEP,61300,61612,61924,62236,62548,62860,63172,63484,63796,...,89.26,89.78,90.30,90.82,91.34,91.85,92.37,32,743,RIOTS
33,PUDUCHERRY,974820,1001784,1028748,1055712,1082676,1109640,1136604,1163568,1190532,...,83.54,84.00,84.46,84.92,85.38,85.85,86.31,479,54116,HURT/GREVIOUS HURT

Data is merged successfully.

In [22]:
#storing crime rate from year 2001 to year 2012 

#creating empty list
crime_rate_2001=[]
crime_rate_2002=[]
crime_rate_2003=[]
crime_rate_2004=[]
crime_rate_2005=[]
crime_rate_2006=[]
crime_rate_2007=[]
crime_rate_2008=[]
crime_rate_2009=[]
crime_rate_2010=[]
crime_rate_2011=[]
crime_rate_2012=[]

#creating dictionary
pop_list={'population_2001':crime_rate_2001,'population_2002':crime_rate_2002,'population_2003':crime_rate_2003,'population_2004':crime_rate_2004,'population_2005':crime_rate_2005,'population_2006':crime_rate_2006,'population_2007':crime_rate_2007,'population_2008':crime_rate_2008,'population_2009':crime_rate_2009,'population_2010':crime_rate_2010,'population_2011':crime_rate_2011,'population_2012':crime_rate_2012}



for i in range(0,34):#running the loop for 34 times
    
    total_crime=df.loc[i,'TOTAL IPC CRIMES'] #storing value present in 'TOTAL IPC CRIMES' column 
    
    for key,value in pop_list.items():#iterating through key and value pair in 'pop_list' dictionary 
        
        population=df.loc[i,key] #storing population
    
        cal=int(round((total_crime/population)*100000,0))#calcuating crime rate  per 100000 people
    
        value.append(cal)#appending

In [23]:
#creating new columns in data frame
df['CRIME RATE 2001']=crime_rate_2001
df['CRIME RATE 2002']=crime_rate_2002
df['CRIME RATE 2003']=crime_rate_2003
df['CRIME RATE 2004']=crime_rate_2004
df['CRIME RATE 2005']=crime_rate_2005
df['CRIME RATE 2006']=crime_rate_2006
df['CRIME RATE 2007']=crime_rate_2007
df['CRIME RATE 2008']=crime_rate_2008
df['CRIME RATE 2009']=crime_rate_2009
df['CRIME RATE 2010']=crime_rate_2010
df['CRIME RATE 2011']=crime_rate_2011
df['CRIME RATE 2012']=crime_rate_2012
df

,STATE/UT,population_2001,population_2002,population_2003,population_2004,population_2005,population_2006,population_2007,population_2008,population_2009,...,CRIME RATE 2003,CRIME RATE 2004,CRIME RATE 2005,CRIME RATE 2006,CRIME RATE 2007,CRIME RATE 2008,CRIME RATE 2009,CRIME RATE 2010,CRIME RATE 2011,CRIME RATE 2012
0,ANDHRA PRADESH,75728400,73094239,70460078,67825917,65191756,62557595,59923434,57289273,54655112,...,2865,2977,3097,3227,3369,3524,3694,3881,4088,4318
1,ARUNACHAL PRADESH,1098328,1126756,1155184,1183612,1212040,1240468,1268896,1297324,1325752,...,2394,2336,2281,2229,2179,2131,2086,2042,2000,1960
2,ASSAM,26638600,27091667,27544734,27997801,28450868,28903935,29357002,29810069,30263136,...,2170,2135,2101,2068,2036,2005,1975,1946,1918,1890
3,BIHAR,82879910,84972382,87064854,89157326,91249798,93342270,95434742,97527214,99619686,...,1546,1510,1475,1442,1411,1380,1351,1324,1297,1271
4,CHHATTISGARH,20834530,21305096,21775662,22246228,22716794,23187360,23657926,24128492,24599058,...,2576,2522,2470,2420,2371,2325,2281,2238,2197,2157
5,GOA,1348900,1359782,1370664,1381546,1392428,1403310,1414192,1425074,1435956,...,2338,2320,2302,2284,2266,2249,2232,2215,2199,2182
6,GUJARAT,50597200,51575842,52554484,53533126,54511768,55490410,56469052,57447694,58426336,...,2637,2589,2542,2497,2454,2412,2372,2333,2295,2258
7,HARYANA,21083900,21550818,22017736,22484654,22951572,23418490,23885408,24352326,24819244,...,2704,2648,2594,2542,2492,2445,2399,2354,2312,2270
8,HIMACHAL PRADESH,6077453,6155358,6233263,6311168,6389073,6466978,6544883,6622788,6700693,...,2486,2455,2425,2396,2367,2340,2312,2286,2260,2234
9,JAMMU & KASHMIR,10070300,10318162,10566024,10813886,11061748,11309610,11557472,11805334,12053196,...,2453,2397,2343,2291,2242,2195,2150,2107,2065,2025
10,JHARKHAND,26946070,27550276,28154482,28758688,29362894,29967100,30571306,31175512,31779718,...,1500,1469,1438,1409,1382,1355,1329,1304,1280,1257
11,KARNATAKA,52734986,53574557,54414128,55253699,56093270,56932841,57772412,58611983,59451554,...,2722,2680,2640,2601,2564,2527,2491,2457,2423,2390
12,KERALA,31839000,31993867,32148734,32303601,32458468,32613335,32768202,32923069,33077936,...,4471,4450,4429,4408,4387,4366,4346,4325,4305,4285
13,MADHYA PRADESH,60385090,61606337,62827584,64048831,65270078,66491325,67712572,68933819,70155066,...,3842,3769,3698,3630,3565,3502,3441,3382,3325,3270
14,MAHARASHTRA,96752500,98314547,99876594,101438641,103000688,104562735,106124782,107686829,109248876,...,2276,2241,2207,2174,2142,2111,2081,2052,2023,1995
15,MANIPUR,2294480,2337207,2379934,2422661,2465388,2508115,2550842,2593569,2636296,...,1474,1448,1423,1398,1375,1352,1330,1309,1289,1269
16,MEGHALAYA,2306540,2372286,2438032,2503778,2569524,2635270,2701016,2766762,2832508,...,1036,1008,983,958,935,913,891,871,852,833
17,MIZORAM,889690,909822,929954,950086,970218,990350,1010482,1030614,1050746,...,2812,2752,2695,2640,2587,2537,2488,2442,2396,2353
18,NAGALAND,1990275,1989307,1988339,1987371,1986403,1985435,1984467,1983499,1982531,...,661,661,661,661,662,662,662,663,663,663
19,ODISHA,36707900,37231845,37755790,38279735,38803680,39327625,39851570,40375515,40899460,...,1716,1693,1670,1648,1626,1605,1584,1564,1545,1526
20,PUNJAB,24289130,24630640,24972150,25313660,25655170,25996680,26338190,26679700,27021210,...,1538,1517,1497,1478,1458,1440,1422,1404,1387,1370
21,RAJASTHAN,56473300,57688071,58902842,60117613,61332384,62547155,63761926,64976697,66191468,...,3151,3087,3026,2967,2911,2856,2804,2753,2705,2658
22,SIKKIM,541902,548480,555058,561636,568214,574792,581370,587948,594526,...,1261,1246,1232,1218,1204,1191,1177,1165,1152,1140
23,TAMIL NADU,62111390,63114146,64116902,65119658,66122414,67125170,68127926,69130682,70133438,...,3213,3164,3116,3069,3024,2980,2938,2896,2856,2817
24,TRIPURA,3191880,3239795,3287710,3335625,3383540,3431455,3479370,3527285,3575200,...,1604,1581,1559,1537,1516,1495,1475,1455,1436,1418
25,UTTAR PRADESH,166053600,169406387,172759174,176111961,179464748,182817535,186170322,189523109,192875896,...,1076,1055,1035,1016,998,980,963,947,931,916
26,UTTARAKHAND,8489100,8651865,8814630,8977395,9140160,9302925,9465690,9628455,9791220,...,1171,1150,1129,1109,1090,1072,1054,1037,1020,1004
27,WEST BENGAL,80221300,81333943,82446586,83559229,84671872,85784515,86897158,88009801,89122444,...,1358,1340,1322,1305,1288,1272,1256,1240,1225,1211
28,A & N ISLANDS,356650,358979,361308,363637,365966,368295,370624,372953,375282,...,2519,2503,2487,2471,2456,2441,2425,2410,2396,2381
29,CHANDIGARH,901080,916440,931800,947160,962520,977880,993240,1008600,1023960,...,4379,4308,4240,4173,4108,4046,3985,3926,3869,3814
30,D & N HAVELI,220963,233152,245341,257530,269719,281908,294097,306286,318475,...,1896,1806,1724,1650,1581,1519,1460,1407,1357,1310
31,DAMAN & DIU,158080,166563,175046,183529,192012,200495,208978,217461,225944,...,1684,1606,1535,1470,1411,1356,1305,1258,1214,1173
32,LAKSHADWEEP,61300,61612,61924,62236,62548,62860,63172,63484,63796,...,1200,1194,1188,1182,1176,1170,1165,1159,1153,1148
33,PUDUCHERRY,974820,1001784,1028748,1055712,1082676,1109640,1136604,1163568,1190532,...,5260,5126,4998,4877,4761,4651,4546,4445,4349,4256

Data is inserted successfully.

In [24]:
#saving data
df.to_csv(r'D:\Files\Phase1_data.csv',index=False)